ARG DOCKER_BASE=ghcr.io/molisens-mosep/humble:dependencies_x86_64
FROM $DOCKER_BASE      

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

COPY x86_64/env.sh /etc/profile.d/env.sh
COPY x86_64/entrypoint /entrypoint

ENTRYPOINT ["/entrypoint"]
CMD ["/bin/sh", "-c", "trap 'exit 147' TERM; tail -f /dev/null & while wait ${!}; [ $? -ge 128 ]; do true; done"]


